version: "3.7"


services:
  # app: 
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - REDIS_ADDR=localhost:6379
  #     - REDIS_DB=0
  #   container_name: cloud-resource-app
  
  redis:
    image: redis/redis-stack:latest
    container_name: cloud-resource-redis
    ports:
      - 6379:6379
    